import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner"

const appearance = {
  elements: {
    card: 'bg-white shadow-lg rounded-lg p-6',
    headerTitle: 'text-2xl font-bold text-center mb-4',
    formFieldInput: 'border border-gray-300 rounded-md p-2 mb-4',
    formButtonPrimary: 'bg-blue-500 text-white py-2 px-4 rounded-md',
  },
};


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider 
      appearance={appearance}
      afterSignOutUrl="/sign-in"
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
